# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc2d1e26d3542de937183ab9aa78856067bc2b350ec2c0a7edfba41babd76e46180cdbb7467137b717a039bc961d5862975f8c2e041c411bf9e4507dc5548b39

test:
  secret_key_base: 6538f760f4a47d7f4f0357494ca525ae690b7fa79bb22a42fd2af18130589e7160cf12d27e25587678d304b4b56aa8db4c67f695d30016a3df4c6aacce040014

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
